CREATE TABLE IF NOT EXISTS developer_api_key (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  api_key VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS developer_webhook (
  id VARCHAR(64) PRIMARY KEY,
  url VARCHAR(512) NOT NULL,
  event VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
