CREATE TABLE IF NOT EXISTS risk_config (
  id TINYINT PRIMARY KEY,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  single_amount_limit DECIMAL(24, 8) NOT NULL DEFAULT 1000,
  blocked_merchants JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channel_route (
  merchant_id VARCHAR(128) PRIMARY KEY,
  mode VARCHAR(16) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_channel_route_mode (mode)
);
